apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: develop
  description: teste catalog-info
spec:
  type: service
  lifecycle: production
  owner: Roberto
  # system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db

